# Generated by Django 6.0.3 on 2026-09-14 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_currency_symbol'),
        ('suppliers', '0002_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql="DELETE FROM suppliers_supplier;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='supplier',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.country', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.currency', verbose_name='Currency'),
        ),
    ]
