# Generated by Django 6.0.3 on 2026-08-21 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_material",
                    models.CharField(
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="Material ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "description",
                    models.TextField(
                        blank=True, max_length=250, verbose_name="Description"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Material",
                "verbose_name_plural": "Materials",
            },
        ),
        migrations.CreateModel(
            name="MaterialType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Material Type Name"
                    ),
                ),
                (
                    "symbol",
                    models.CharField(max_length=10, unique=True, verbose_name="Symbol"),
                ),
            ],
            options={
                "verbose_name": "Material Type",
                "verbose_name_plural": "Material Types",
            },
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Unit Name"
                    ),
                ),
                (
                    "symbol",
                    models.CharField(max_length=10, unique=True, verbose_name="Symbol"),
                ),
            ],
            options={
                "verbose_name": "Unit",
                "verbose_name_plural": "Units",
            },
        ),
    ]
