# Generated by Django 6.0.3 on 2026-08-06 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0002_alter_material_id_material"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaterialType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Material Type Name"
                    ),
                ),
                (
                    "symbol",
                    models.CharField(max_length=10, unique=True, verbose_name="Symbol"),
                ),
            ],
            options={
                "verbose_name": "Material Type",
                "verbose_name_plural": "Material Types",
            },
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Unit Name"
                    ),
                ),
                (
                    "symbol",
                    models.CharField(max_length=10, unique=True, verbose_name="Symbol"),
                ),
            ],
            options={
                "verbose_name": "Unit",
                "verbose_name_plural": "Units",
            },
        ),
        migrations.RemoveField(
            model_name="material",
            name="material_type",
        ),
        migrations.RemoveField(
            model_name="material",
            name="status",
        ),
        migrations.RemoveField(
            model_name="material",
            name="unit",
        ),
    ]
