# Generated by Django 6.0.3 on 2026-08-06 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("materials", "0003_materialtype_unit_remove_material_material_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="material_type",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="materials.materialtype",
                verbose_name="Material type",
            ),
        ),
        migrations.AddField(
            model_name="material",
            name="status",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.status",
                verbose_name="Status",
            ),
        ),
        migrations.AddField(
            model_name="material",
            name="unit",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="materials.unit",
                verbose_name="Unit measure",
            ),
        ),
    ]
