# Generated by Django 6.0.3 on 2026-09-17 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("purchases", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="linesgoodsreceipt",
            old_name="id_goods_recipt",
            new_name="id_goods_receipt",
        ),
    ]
