# Generated by Django 6.0.3 on 2026-09-08 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_inventorymovements_currency_inventorymovements_price"),
        ("materials", "0002_initial"),
        ("purchases", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GoodsReceiptStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                (
                    "symbol",
                    models.CharField(blank=True, max_length=100, verbose_name="Symbol"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Goods Receipt Status",
                "verbose_name_plural": "Goods Receipt Status",
            },
        ),
        migrations.CreateModel(
            name="GoodsReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_goods_receipt",
                    models.CharField(max_length=10, verbose_name="ID Goods Receipt"),
                ),
                ("receipt_date", models.DateField(verbose_name="Receipt Date")),
                (
                    "supplier_delivery_note",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Estimated delivery date",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "id_purchase_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="purchases.purchaseorder",
                        verbose_name="ID Purchase Order",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="purchases.goodsreceiptstatus",
                        verbose_name="Status",
                    ),
                ),
            ],
            options={
                "verbose_name": "Goods Receipt",
                "verbose_name_plural": "Goods Receipts",
            },
        ),
        migrations.CreateModel(
            name="LinesGoodsReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_goods_receipt_line",
                    models.CharField(
                        max_length=10, verbose_name="ID Goods Receipt Line"
                    ),
                ),
                (
                    "received_quantity",
                    models.IntegerField(verbose_name="Received Quantity"),
                ),
                (
                    "inventory_movement_ref",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Inventory Movement ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "id_goods_recipt",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lines",
                        to="purchases.goodsreceipt",
                        verbose_name="Goods Receipt",
                    ),
                ),
                (
                    "id_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.locationinventory",
                        verbose_name="Destination Location",
                    ),
                ),
                (
                    "id_material",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="materials.material",
                        verbose_name="Material",
                    ),
                ),
                (
                    "id_purchase_order_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="purchases.linespurchaseorder",
                        verbose_name="Purchase Order Line",
                    ),
                ),
                (
                    "unit_material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="materials.unit",
                        verbose_name="Unit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Line Goods Receipt",
                "verbose_name_plural": "Lines Goods Receipts",
            },
        ),
    ]
