# Generated by Django 6.0.3 on 2026-08-21 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InventoryMovements",
            fields=[
                (
                    "id_inventory_movement",
                    models.CharField(
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Inventory Movement ID",
                    ),
                ),
                ("quantity", models.IntegerField(verbose_name="Quantity")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Inventory Movement",
                "verbose_name_plural": "Inventory Movements",
            },
        ),
        migrations.CreateModel(
            name="LocationInventory",
            fields=[
                (
                    "id_location",
                    models.CharField(
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Location ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("code", models.CharField(max_length=20, verbose_name="Code")),
                (
                    "main_location",
                    models.BooleanField(default=False, verbose_name="Main Location"),
                ),
                ("location", models.TextField(blank=True, verbose_name="Address")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Inventory Location",
                "verbose_name_plural": "Inventory Locations",
            },
        ),
        migrations.CreateModel(
            name="MovementType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Name")),
                ("symbol", models.CharField(max_length=10, verbose_name="Symbol")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Movement Type",
                "verbose_name_plural": "Movement Types",
            },
        ),
    ]
