# Generated by Django 6.0.3 on 2026-08-21 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("inventory", "0001_initial"),
        ("materials", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="inventorymovements",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="inventorymovements",
            name="id_material",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="materials.material",
                verbose_name="Material ID",
            ),
        ),
        migrations.AddField(
            model_name="inventorymovements",
            name="unit_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="materials.unit",
                verbose_name="Unit Type",
            ),
        ),
        migrations.AddField(
            model_name="locationinventory",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="locationinventory",
            name="status",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.status",
                verbose_name="Status",
            ),
        ),
        migrations.AddField(
            model_name="inventorymovements",
            name="id_location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="inventory.locationinventory",
                verbose_name="Location ID",
            ),
        ),
        migrations.AddField(
            model_name="movementtype",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="inventorymovements",
            name="movement_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="inventory.movementtype",
                verbose_name="Movement ID",
            ),
        ),
    ]
