# Generated by Django 6.0.3 on 2026-09-08 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("inventory", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventorymovements",
            name="currency",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.currency",
                verbose_name="Currency",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="inventorymovements",
            name="price",
            field=models.FloatField(default=0.0, verbose_name="Price"),
        ),
    ]
