# Generated by Django 6.0.3 on 2026-08-19 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_customer",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Customer ID"
                    ),
                ),
                (
                    "legal_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Legal Name"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("tax_id", models.CharField(max_length=30, verbose_name="Tax ID")),
                ("country", models.CharField(max_length=60, verbose_name="Country")),
                (
                    "state_province",
                    models.CharField(max_length=60, verbose_name="State/Province"),
                ),
                ("city", models.CharField(max_length=100, verbose_name="City")),
                ("address", models.CharField(max_length=150, verbose_name="Address")),
                ("zip_code", models.IntegerField(verbose_name="Zip Code")),
                ("phone", models.IntegerField(verbose_name="Phone")),
                ("email", models.EmailField(max_length=150, verbose_name="Email")),
                (
                    "contact_name",
                    models.CharField(max_length=150, verbose_name="Contact name"),
                ),
                (
                    "contact_role",
                    models.CharField(max_length=150, verbose_name="Contact role"),
                ),
                ("category", models.CharField(max_length=150, verbose_name="Category")),
                (
                    "payment_terms",
                    models.CharField(max_length=150, verbose_name="Payment terms"),
                ),
                ("currency", models.CharField(max_length=150, verbose_name="Currency")),
                (
                    "payment_method",
                    models.CharField(max_length=150, verbose_name="Payment method"),
                ),
                (
                    "bank_account",
                    models.CharField(max_length=150, verbose_name="Bank account"),
                ),
                ("status", models.CharField(max_length=50, verbose_name="Status")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer",
                "verbose_name_plural": "Customers",
            },
        ),
    ]
