# Generated by Django 6.0.3 on 2026-08-21 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountGroup",
            fields=[
                (
                    "id_account_group",
                    models.CharField(
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Account Groupe ID",
                    ),
                ),
                ("name", models.CharField(max_length=10, verbose_name="Name")),
                (
                    "code_prefix",
                    models.CharField(max_length=10, verbose_name="Code Prefix"),
                ),
                ("description", models.TextField(verbose_name="Description")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Account Group",
                "verbose_name_plural": "Account Groups",
            },
        ),
        migrations.CreateModel(
            name="AccountNature",
            fields=[
                (
                    "id_account_nature",
                    models.CharField(
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Account Nature ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Name")),
                ("symbol", models.CharField(max_length=10, verbose_name="Symbol")),
                (
                    "effect_on_balance",
                    models.TextField(verbose_name="Effect on Balance"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Account Nature",
                "verbose_name_plural": "Account Natures",
            },
        ),
        migrations.CreateModel(
            name="AccountType",
            fields=[
                (
                    "id_account_type",
                    models.CharField(
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Account Type ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Account Type",
                "verbose_name_plural": "Account Types",
            },
        ),
        migrations.CreateModel(
            name="AccountAccount",
            fields=[
                (
                    "id_account",
                    models.CharField(
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Account ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("code", models.CharField(max_length=20, verbose_name="Code")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "is_control_account",
                    models.BooleanField(
                        default=False, verbose_name="Is Control Account"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "country_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.country",
                        verbose_name="Country ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Account",
                "verbose_name_plural": "Accounts",
            },
        ),
    ]
