# Generated by Django 6.0.3 on 2026-08-21 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounting", "0001_initial"),
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="accountaccount",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="accountaccount",
            name="currency_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="core.currency",
                verbose_name="Currency ID",
            ),
        ),
        migrations.AddField(
            model_name="accountaccount",
            name="parent_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounting.accountaccount",
                verbose_name="Parent Account",
            ),
        ),
        migrations.AddField(
            model_name="accountaccount",
            name="status",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.status",
                verbose_name="Status",
            ),
        ),
        migrations.AddField(
            model_name="accountgroup",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="accountaccount",
            name="account_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="accounting.accountgroup",
                verbose_name="Account Groupe",
            ),
        ),
        migrations.AddField(
            model_name="accountnature",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="accountaccount",
            name="nature",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="accounting.accountnature",
                verbose_name="Account Nature",
            ),
        ),
        migrations.AddField(
            model_name="accounttype",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="accountaccount",
            name="account_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="accounting.accounttype",
                verbose_name="Account Type",
            ),
        ),
    ]
